### ISSUE TITLE
请问一下为什么records中的summary.csv中会出现大量routing failure

### ISSUE THREAD

**Issue by lily410** [Software-Aurora-Lab/DoppelTest#2]
config.py未改动，12h共跑90generation，summary的结果如图，论文中这个错误好像只占很小一部分，不知道什么原因导致的，谢谢！
![image](https://github.com/Software-Aurora-Lab/DoppelTest/assets/111175769/b01ff6f7-46ff-45e0-b645-bce3c2c977cc)

**Comment by YuqiHuai** [comment]
您好，如果您用的是Apollo 7.0中的Borregas Avenue的话，论文实验过程中统计结果时为了去重避免多报（仔细看的话routing failure都是由2条路造成的），我们不论多少routing failure都按2个计算。这个bug已经在https://github.com/ApolloAuto/apollo/issues/14529修复，后来实验也是在修复后的地图上跑的，否则会出现您看到的这种情况routing failure占大部分。

**Comment by lily410** [comment]
是这样的，十分感谢！
