### ISSUE TITLE
apollo车辆无法移动，速度为零

### ISSUE THREAD

**Issue by E00N777** [Software-Aurora-Lab/DoppelTest#3]
我按照您在代码库和文档库中的readme进行了复现，但是出现了一个奇怪的问题。
我的复现的所有环境均是按照您所要求准备的，当我python main_ga.py时测试可以正常进行，当我完成了20轮的遗传算法后，出现了在 [Apollo Issue #14529](https://github.com/ApolloAuto/apollo/issues/14529)相同的问题，但是不同的是在测试过程中5个apollo实例均是静止不动的，速度均是0m/s，几乎所有轮次场景中的实例均是如此。我不知道是哪里出现了问题。
我正在尝试阅读您的源码来找到问题的所在，您在实验室有遇到过类似的问题吗？希望您能给我一些帮助

**Comment by YuqiHuai** [comment]
您好

可能是场景都卡在这个无法完成的路径请求了，但5个同时卡住确实几率较小，建议看下这个场景中被卡住的实例收到了什么routing request。代码当前可能会删掉一些record，可以暂时修改保留所有record。

文章中的实验在一开始发现路径问题之后我们先是修复了这个地图以此保证不会经常出现这个bug，要不然会重复生成大量车不动的场景。
