### ISSUE TITLE
test_main.py error (DoppelTest) (Instance apollo_dev_ROUTE_0 is not running)

### ISSUE THREAD

**Issue by pakpool** [Software-Aurora-Lab/DoppelTest#8]
I am trying to run DoppelTest. I have followed the instructions mentioned in the INSTALL file to recreate the experiment but when i try to Verify the framework is runnable via `python test_main.py` i get the folowing error

apollo_dev_ROUTE_0: starting
Traceback (most recent call last):
  File "/home/umer/Downloads/DoppelTest-2023.02.20/test_main.py", line 29, in <module>
    ctn.start_instance()
  File "/home/umer/Downloads/DoppelTest-2023.02.20/apollo/ApolloContainer.py", line 85, in start_instance
    self.logger.debug(f'Started running at {self.ip}')
  File "/home/umer/Downloads/DoppelTest-2023.02.20/apollo/ApolloContainer.py", line 61, in ip
    assert self.is_running(
AssertionError: Instance apollo_dev_ROUTE_0 is not running.

however i can see that the container is running when use docker ps

:~/Apollo_DT$ docker ps
CONTAINER ID   IMAGE                                                                      COMMAND       CREATED          STATUS          PORTS     NAMES
1415f79b6ac9   apolloauto/apollo:dev-x86_64-18.04-20210914_1336   "/bin/bash"   36 minutes ago   Up 36 minutes             apollo_dev_ROUTE_0

**Comment by YuqiHuai** [comment]
Hi, thank you for your interest! I have seen this issue occasionally but typically this issue did not consistently show up for me. It might be better to add some sleep statements to wait longer.
—-
I’m traveling at the moment therefore I can’t resolve the issue immediately. But I’ll look at this when I return to work.

**Comment by pakpool** [comment]
I have added sleep statements to wait longer but no  use. Error is still there.
And this issue is consistent for me. I am trying for 2 days now.Please do reply when you get back to work.

**Comment by YuqiHuai** [comment]
@pakpool I am sorry about this happening for you for 2 days. I don't have a Ubuntu machine with me at the moment but I want to make sure I don't block you from moving forward therefore I'll still try to reply to you and help localize potential issues. I am ok with setting up a Zoom meeting with you and debugging together live. Meanwhile, can you try to add some lines to this function and see what is going on
```python
    def is_running(self) -> bool:
        """
        Checks if the container is running

        :returns: True if running, False otherwise
        :rtype: bool
        """
        try:
            return docker.from_env().containers.get(self.container_name).status == 'running'
        except:
            return False
```
Alternatively, you can check what is the output of 
```python
docker.from_env().containers.get("apollo_dev_ROUTE_0")
```
I suspect the above line is throwing some error and causing this function to incorrectly return False even when the container is clearly up and running.

**Comment by pakpool** [comment]
Found the problem:
 i dont know why but Docker was configured to use a different Docker socket (unix:///home/umer/.docker/desktop/docker.sock) than the default one (/var/run/docker.sock).
 so To fix this, i set the DOCKER_HOST environment variable to point to the Docker Desktop socket
 
 but now i am getting following error
 
 
![image](https://github.com/user-attachments/assets/6a0739da-7819-4c2c-b024-2ff3b57fca13)

**Comment by YuqiHuai** [comment]
To fix this issue you would need to check if dreamview is up and running at something like 172.17.0.2:8888

you would need to check the IP address of the container.

**Comment by pakpool** [comment]
the container is running at 172.17.0.2. and
mer@umer-3640-Tower:~/Desktop$ docker exec apollo_dev_ROUTE_0 lsof -i :8888
COMMAND   PID USER   FD   TYPE DEVICE SIZE/OFF NODE NAME
dreamview 216 root    3u  IPv4 448527      0t0  TCP *:8888 (LISTEN)

but https://172.17.0.2:8888 show nothing

umer@umer-3640-Tower:~/Desktop$ curl http://localhost:8888
curl: (7) Failed to connect to localhost port 8888 after 0 ms: Connection refused

**Comment by YuqiHuai** [comment]
Thanks for the update. If you go into the container and launch dreamview, it should be accessible at 172.17.0.2:8888

based in the information you provided, dream view isn’t accessible and caused the error. Have you ever manually installed Apollo 7.0 on this machine?

**Comment by pakpool** [comment]
yes i have manually installed the apollo 7. At that time when i first tried i was not able to see dreamview . and docker ps showed no port in the port section.
then i run the container using
docker run -it --name apollo_dev_umer --privileged -p 8888:8888 ............... (manually added the port)
then i was able to see the dreamview and able to play the recording mentioned in that tutorial.
one more thing i am using docker desktop. Do you think that can be the problem?

**Comment by YuqiHuai** [comment]
Yes, that would be the problem. You should be able to see dreamview when you manually install and launch dreamview. But the solution you used (manually adding the port) shouldn’t be the problem, because by default the launch script uses —net host so all ports are by default accessible.

I would suggest installing docker differently, for example using get_docker.sh or spend more time figure out what you need to do under current setting to just launch and be able to access dreamview.

**Comment by pakpool** [comment]
hi, i was able to fix the problem by updating the docker. The requirement file mentioned to install docker 5.0. I updated it to latest version and every thing worked fine after that.

Now i want to use a new map in this framework. i have converted the map to apollo map according to this https://github.com/daohu527/apollo_map. I just want to know if i have to change some thing in the Doppeltest code. Because as thing stands i am able to see the option of the new map "Town1"  but it is not showing the map. as you can see in the screenshot

![Screenshot from 2024-08-15 16-58-59](https://github.com/user-attachments/assets/1dcb6404-9380-4a14-b99c-d261016f433e)

also i noticed that i am only able to switch to san_mateo and Demo maps. Others i can see.

**Comment by YuqiHuai** [comment]
Hi @pakpool , apologies for the delayed response. To use a new map in DoppelTest, you should consider:
1. Moving the map to `/data/maps`
2. Changing the name of the map here https://github.com/Software-Aurora-Lab/DoppelTest/blob/e9d0f9e13058cea33d617e5601b91a09e4a82651/config.py#L51

It may take some time when you are running the new map for the first time (depending how large the map is).
---
In the screenshot you showed, you selected "Town1" but the map lanes are not showing because the vehicle is not initialized at the right coordinate. You can consider turning on SimControl to see if it will be able to find a valid initial location for you. DoppelTest should be able to automatically find some valid initial locations.

**Comment by pakpool** [comment]
Thanks for your reply.
I was able to load the map.
Can you please guide me how can i start the ADS from a specific location.
And can i add one or two NPC in you framework?

**Comment by YuqiHuai** [comment]
@pakpool Sounds good.

> Can I add one or two NPC in your framework? A car that is not ADS and can be manually controlled.

In DoppelTest implementation, all cars are AVs but the pedestrian is a simplified NPC. You can check out how the pedestrian is implemented to implement your manual-controlled NPC vehicles but you need to implement it yourself. In [another project](https://github.com/Software-Aurora-Lab/scenoRITA-7.0) cars are not AVs and there is an implementation that computes NPC (car/pedestrian) trajectory and transforms them into Apollo's perception messages.

**Comment by pakpool** [comment]
can i see the implementation of obstacle (function) in scenoRITA?
i open the link you mentioned above but do not see the required file?

**Comment by YuqiHuai** [comment]
@pakpool sure, take a look at this function https://github.com/Software-Aurora-Lab/scenoRITA-7.0/blob/fe24d3426aaa47d533dfcb76a04ad946a7c6cbfc/src/scenoRITA/components/scenario_generator.py#L341 and how it is being used. This is where perception messages are being generated for obstacles.
